version: "3.8"

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    depends_on:
      - frontend
    networks:
      - ai-news-network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_WS_URL=ws://localhost:3001
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    networks:
      - ai-news-network

networks:
  ai-news-network:
    driver: bridge
